"""Stage 1: the artifacts that get ESX onto bare metal.

The same inventory that renders an SddcSpec renders these, so the operator
describes the lab once and the two outputs cannot drift.

This module emits text. It never writes to a boot server, never opens a
socket, and never powers anything on -- publishing the files and turning the
hosts on are the operator's, and a host with no BMC needs a switched PDU for
the latter anyway.

Two things the spike (2026-09-17) settled that shape everything here:

* VCF does not image bare metal. ESX must already be installed and
  basic-configured before a host can be commissioned, so this fills a real
  gap rather than duplicating the Installer.
* The ESX installer does not validate TLS for `ks=https://`. The provisioning
  VLAN is the trust boundary, not the transport -- which is why the root
  password stays a `${reference}` all the way to the file the operator
  publishes, and why the manifest says so out loud.
"""
from __future__ import annotations

import ipaddress
from dataclasses import dataclass

from .findings import Finding, Result
from .render import InsecureCredentialError, _credential
from .rules import finding_for

DEFAULT_ESX_VERSION = "9.1.1.0"

# One place for every kickstart directive, so correcting the syntax is a
# single edit rather than a hunt. Real hardware is the only authority here.
_KICKSTART = """\
# ESX kickstart for {fqdn}
# Generated by vcfspec from the lab inventory. Do not hand-edit: regenerate.
#
# The root password below is a ${{reference}}. Substitute it when you publish
# this file, and remember the file sits on an unauthenticated HTTP server that
# every host on the provisioning VLAN can read.
vmaccepteula
rootpw {root_password}
install --disk={boot_disk} --overwritevmfs --novmfsondisk
network --bootproto=static --ip={ip} --netmask={netmask} --gateway={gateway} \
--nameserver={nameservers} --hostname={fqdn} --addvmportgroup=0{vlan_opt}
reboot

%firstboot --interpreter=busybox
# Enough to make the host commissionable by VCF; everything else is the
# Installer's job once it takes over.
esxcli system ntp set --enabled=yes {ntp_opts}
vim-cmd hostsvc/enable_ssh
vim-cmd hostsvc/start_ssh
"""

_BOOT_CFG = """\
# UEFI HTTP boot config for {fqdn} ({mac})
# Place at: {path}
bootstate=0
title=Loading ESX {esx_version} for {fqdn}
timeout=5
prefix={prefix}
kernel=/b.b00
kernelopt=ks={ks_url} ip={ip} netmask={netmask} gateway={gateway}{vlan_boot}
"""


@dataclass(frozen=True, slots=True)
class ProvisioningArtifacts:
    """What the operator publishes, plus what stopped us generating it.

    `findings` is not an afterthought: a host missing `provisioningMac` or
    `bootDisk` yields no files for that host, and saying so is more useful
    than emitting a kickstart that would install to the wrong device.
    """

    kickstarts: dict[str, str]
    boot_configs: dict[str, str]
    manifest: str
    findings: tuple[Finding, ...]

    @property
    def result(self) -> Result:
        return Result(self.findings)


def _netmask(subnet: str) -> str | None:
    try:
        return str(ipaddress.ip_network(subnet, strict=False).netmask)
    except (ValueError, TypeError):
        return None


def _mapping(value: object) -> dict:
    return value if isinstance(value, dict) else {}


def render_provisioning(inventory: dict) -> ProvisioningArtifacts:
    """Render one kickstart per host and one boot config per MAC."""
    findings: list[Finding] = []
    kickstarts: dict[str, str] = {}
    boot_configs: dict[str, str] = {}

    prov = _mapping(inventory.get("provisioning"))
    boot_url = str(prov.get("bootServerUrl", "")).rstrip("/")
    esx_version = str(prov.get("esxVersion") or DEFAULT_ESX_VERSION)
    if not boot_url:
        findings.append(finding_for("VCF-PROV-NO-BOOT-SERVER", "/provisioning"))
        return ProvisioningArtifacts({}, {}, "", tuple(findings))

    mgmt = _mapping(_mapping(inventory.get("networks")).get("management"))
    netmask = _netmask(str(mgmt.get("subnet", "")))
    gateway = mgmt.get("gateway")
    vlan = mgmt.get("vlan")
    if netmask is None or not gateway:
        findings.append(finding_for("VCF-PROV-NO-MGMT-NETWORK",
                                    "/networks/management"))
        return ProvisioningArtifacts({}, {}, "", tuple(findings))

    dns = _mapping(inventory.get("dns"))
    subdomain = str(dns.get("subdomain", "")).strip(".")
    nameservers = ",".join(str(x) for x in (dns.get("nameservers") or []))
    ntp = [str(x) for x in (_mapping(inventory.get("ntp")).get("servers") or [])]
    ntp_opts = " ".join(f"--server={x}" for x in ntp)
    # Same refusal render() makes, and it matters more here: this file is
    # published to an HTTP server the whole provisioning VLAN can read.
    root_password = _credential(_mapping(inventory.get("credentials")), "esxRoot")

    # A VLAN of 0 or 1 is untagged; emitting `--vlanid=1` makes the installer
    # tag a network the switch expects untagged, which strands the host with
    # no console to recover it.
    tagged = isinstance(vlan, int) and vlan > 1
    vlan_opt = f" --vlanid={vlan}" if tagged else ""
    vlan_boot = f" vlanid={vlan}" if tagged else ""

    for index, host in enumerate(inventory.get("hosts") or []):
        host = _mapping(host)
        name, path = host.get("name", ""), f"/hosts/{index}"
        mac = str(host.get("provisioningMac", "")).lower()
        boot_disk = host.get("bootDisk")
        if not mac:
            findings.append(finding_for("VCF-PROV-NO-MAC", path, host=name))
            continue
        if not boot_disk:
            findings.append(finding_for("VCF-PROV-NO-BOOT-DISK", path, host=name))
            continue

        fqdn = f"{name}.{subdomain}" if subdomain else str(name)
        ks_name = f"ks-{name}.cfg"
        ks_url = f"{boot_url}/{ks_name}"
        kickstarts[ks_name] = _KICKSTART.format(
            fqdn=fqdn, root_password=root_password, boot_disk=boot_disk,
            ip=host.get("mgmtIp", ""), netmask=netmask, gateway=gateway,
            nameservers=nameservers, vlan_opt=vlan_opt, ntp_opts=ntp_opts,
        )
        # UEFI HTTP boot selects per-MAC by filename, lowercase and
        # dash-separated, the same convention PXE has always used.
        cfg_name = f"boot-{mac.replace(':', '-')}.cfg"
        boot_configs[cfg_name] = _BOOT_CFG.format(
            fqdn=fqdn, mac=mac, path=f"{boot_url}/{cfg_name}",
            esx_version=esx_version, prefix=boot_url, ks_url=ks_url,
            ip=host.get("mgmtIp", ""), netmask=netmask, gateway=gateway,
            vlan_boot=vlan_boot,
        )

    return ProvisioningArtifacts(kickstarts, boot_configs,
                                 _manifest(boot_url, esx_version, kickstarts,
                                           boot_configs),
                                 tuple(findings))


def _manifest(boot_url: str, esx_version: str, kickstarts: dict[str, str],
              boot_configs: dict[str, str]) -> str:
    lines = [
        f"# ESX provisioning artifacts -- ESX {esx_version}",
        f"# Publish all of these under {boot_url}/",
        "#",
        "# BEFORE PUBLISHING: substitute the ${reference} in each kickstart's",
        "# rootpw line. These files are served over unauthenticated HTTP and",
        "# the ESX installer does not validate TLS, so anything on the",
        "# provisioning VLAN can read whatever you put here.",
        "#",
        "# Each host also needs one BIOS pass first: UEFI mode, HTTP boot",
        "# enabled, NIC ahead of disk in boot order, AC recovery = always on.",
        "",
    ]
    for name in sorted(boot_configs):
        lines.append(f"{name}")
    for name in sorted(kickstarts):
        lines.append(f"{name}")
    return "\n".join(lines) + "\n"
