#!/usr/bin/env bash
# tester-vm-dnat.sh — add/remove the inbound port-forward for the tester guest.
#
# WHY THIS IS NOT IN /etc/network/interfaces.d/sdn: that file is GENERATED by
# PVE SDN from /etc/pve/sdn/.running-config. The next SDN apply rewrites it and
# a rule added there disappears silently — presenting as "the tester cannot SSH
# in" with no obvious cause. A systemd unit survives that.
#
# iptables, not nft: the host's existing SNAT rules are iptables and
# nftables.service is disabled. Match the idiom in place.
set -Eeuo pipefail
PORT="${TESTER_SSH_PORT:-2222}"
DEST="${TESTER_DEST:-10.78.0.10:22}"
UPLINK="${TESTER_UPLINK:-vmbr0}"

rule=(PREROUTING -i "$UPLINK" -p tcp --dport "$PORT" -j DNAT --to-destination "$DEST")

case "${1:-}" in
  add) iptables -t nat -C "${rule[@]}" 2>/dev/null || iptables -t nat -A "${rule[@]}" ;;
  del) iptables -t nat -C "${rule[@]}" 2>/dev/null && iptables -t nat -D "${rule[@]}" || true ;;
  *)   echo "usage: $0 add|del" >&2; exit 2 ;;
esac
