#!/usr/bin/env bash
# tester-vm-dnat.sh — add/remove the inbound port-forward for the tester guest.
#
# WHY THIS IS NOT IN /etc/network/interfaces.d/sdn: that file is GENERATED by
# PVE SDN from /etc/pve/sdn/.running-config. The next SDN apply rewrites it and
# a rule added there disappears silently — presenting as "the tester cannot SSH
# in" with no obvious cause. A systemd unit survives that.
#
# iptables, not nft: the host's existing SNAT rules are iptables and
# nftables.service is disabled. Match the idiom in place.
set -Eeuo pipefail
PORT="${TESTER_SSH_PORT:-2222}"
DEST="${TESTER_DEST:-10.78.0.10:22}"
UPLINK="${TESTER_UPLINK:-vmbr0}"

rule=(PREROUTING -i "$UPLINK" -p tcp --dport "$PORT" -j DNAT --to-destination "$DEST")

case "${1:-}" in
  add) iptables -t nat -C "${rule[@]}" 2>/dev/null || iptables -t nat -A "${rule[@]}" ;;
  del)
    # This is the rollback path: a silent failure here means the exposure
    # does not actually close. Only "the rule was already gone" is quiet --
    # a real -D failure (lock contention, permissions, ...) must be loud.
    if iptables -t nat -C "${rule[@]}" 2>/dev/null; then
      iptables -t nat -D "${rule[@]}" || {
        echo "tester-vm-dnat: FAILED to delete DNAT rule -- port ${PORT} may still be forwarded to ${DEST}" >&2
        exit 1
      }
    fi
    ;;
  *)   echo "usage: $0 add|del" >&2; exit 2 ;;
esac
