#!/usr/bin/env bash
# 53-lxc-router.sh — Phase 7 of setup-runbook.md.
#
# Provision LXC 153 (llm-router):
#   - Lightweight LXC (2 cores / 4 GB), no GPU passthrough
#   - Python venv + FastAPI + httpx
#   - Deploy router app from scripts/files/router-app.py
#   - systemd unit that points at the AMD and NV LXC IPs

set -Eeuo pipefail
LGC_DIR="${LGC_DIR:-$(cd "$(dirname "$0")" && pwd)}"
# shellcheck source=lib/common.sh
source "$LGC_DIR/lib/common.sh"

require_root
require_pve_host
load_config

ROUTER_VMID="${ROUTER_VMID:-153}"
ROUTER_HOSTNAME="${ROUTER_HOSTNAME:-llm-router}"
ROUTER_CORES="${ROUTER_CORES:-2}"
ROUTER_MEMORY="${ROUTER_MEMORY:-4096}"
ROUTER_ROOTFS_SIZE="${ROUTER_ROOTFS_SIZE:-8}"
LXC_STORAGE="${LXC_STORAGE:-local-lvm}"   # V620-only: ext4 + LVM-thin (was local-zfs)
BRIDGE="${BRIDGE:-vmbr0}"
LXC_TEMPLATE_NAME="${LXC_TEMPLATE_NAME:-ubuntu-24.04-standard_24.04-2_amd64.tar.zst}"
LXC_TEMPLATE_STORAGE="${LXC_TEMPLATE_STORAGE:-local}"

# V620-only: all upstream URLs target LXC 151 (the V620 LXC) on different ports.
# FAST_URL + FAST_ALIASES removed (no more 3060 fast-chat tier).
AMD_IP="${AMD_IP:-192.168.6.151}"
V620_URL="${V620_URL:-http://${AMD_IP}:8080}"
EMBED_URL="${EMBED_URL:-http://${AMD_IP}:8082}"
RERANK_URL="${RERANK_URL:-http://${AMD_IP}:8083}"
KEEPALIVE_INTERVAL="${KEEPALIVE_INTERVAL:-12}"

# Admission control + rate limit (consumed by router-app.py rewrite).
# CHAT_CONCURRENCY=2 supports parallel agent + sub-agent calls from Cline/OpenCode
# style tools (single-user but with internal parallelism). Each chat gets ~33 t/s
# at the upstream's --parallel 4 setup, vs 66 t/s if alone.
CHAT_CONCURRENCY="${CHAT_CONCURRENCY:-2}"
EMBED_CONCURRENCY="${EMBED_CONCURRENCY:-4}"
MAX_CHAT_INPUT_TOKENS="${MAX_CHAT_INPUT_TOKENS:-120000}"
MAX_EMBED_INPUT_TOKENS="${MAX_EMBED_INPUT_TOKENS:-16384}"  # must match EMBED_CTX/EMBED_PARALLEL per-slot ctx on LXC 151
RATE_LIMIT_CHAT="${RATE_LIMIT_CHAT:-60/minute}"
RATE_LIMIT_EMBED="${RATE_LIMIT_EMBED:-200/minute}"
PROXMOX_HOST_IP="${PROXMOX_HOST_IP:-192.168.6.150}"
METRICS_ALLOWED_IPS="${METRICS_ALLOWED_IPS:-127.0.0.1,${PROXMOX_HOST_IP}}"

# AMD_VMID needed to fetch LLAMACPP_API_KEY from LXC 151 in phase_7_1_5
AMD_VMID="${AMD_VMID:-151}"

APP_SRC="$LGC_DIR/files/router-app.py"
[[ -r "$APP_SRC" ]] || die "router-app.py not found at $APP_SRC"

phase_7_1_create() {
  step "7.1 — Create LXC $ROUTER_VMID ($ROUTER_HOSTNAME)"
  if lxc_exists "$ROUTER_VMID"; then
    skip "LXC $ROUTER_VMID already exists."
    return 0
  fi
  pct create "$ROUTER_VMID" "$LXC_TEMPLATE_STORAGE:vztmpl/$LXC_TEMPLATE_NAME" \
    --hostname "$ROUTER_HOSTNAME" \
    --cores "$ROUTER_CORES" \
    --memory "$ROUTER_MEMORY" \
    --rootfs "${LXC_STORAGE}:${ROUTER_ROOTFS_SIZE}" \
    --net0 "name=eth0,bridge=${BRIDGE},firewall=0,ip=dhcp,type=veth" \
    --features nesting=0 \
    --unprivileged 1 \
    --ostype ubuntu \
    --start 1
  sleep 5
}

phase_7_1_5_api_keys() {
  step "7.1.5 — Generate ROUTER_API_KEY + fetch LLAMACPP_API_KEY from LXC 151"
  pct exec "$ROUTER_VMID" -- bash -se <<'GUEST'
    set -Eeuo pipefail
    mkdir -p /etc
    # Idempotent: only generate if not present
    if ! grep -q "^ROUTER_API_KEY=" /etc/router.env 2>/dev/null; then
      echo "ROUTER_API_KEY=$(openssl rand -hex 32)" >> /etc/router.env
    fi
    chmod 600 /etc/router.env
    chown root:root /etc/router.env
GUEST

  # Pull LLAMACPP_API_KEY from LXC 151 (must have been generated by 51-lxc-amd.sh).
  # Strip any whitespace/CR — awk output can carry a trailing newline that breaks sed.
  local llamacpp_key
  llamacpp_key="$(pct exec "$AMD_VMID" -- awk -F= '/^LLAMACPP_API_KEY=/{print $2}' /etc/llamacpp.env 2>/dev/null | tr -d '[:space:]' || true)"
  if [[ -z "$llamacpp_key" ]]; then
    warn "LLAMACPP_API_KEY not found on LXC $AMD_VMID. The router will fail upstream auth until 51-lxc-amd.sh has run and generated it. Continuing anyway."
  else
    pct exec "$ROUTER_VMID" -- env "LLAMACPP_KEY=$llamacpp_key" bash -se <<'GUEST'
      set -Eeuo pipefail
      : "${LLAMACPP_KEY:?LLAMACPP_KEY not propagated from host}"
      if grep -q "^LLAMACPP_API_KEY=" /etc/router.env 2>/dev/null; then
        sed -i "s|^LLAMACPP_API_KEY=.*|LLAMACPP_API_KEY=${LLAMACPP_KEY}|" /etc/router.env
      else
        echo "LLAMACPP_API_KEY=${LLAMACPP_KEY}" >> /etc/router.env
      fi
      chmod 600 /etc/router.env
GUEST
  fi
  ok "API keys persisted to /etc/router.env on LXC $ROUTER_VMID"
}

phase_7_2_python_env() {
  step "7.2 — Python venv + FastAPI + slowapi + Prometheus instrumentator"
  ensure_lxc_started "$ROUTER_VMID"

  pct exec "$ROUTER_VMID" -- bash -se <<'GUEST'
    set -Eeuo pipefail
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt install -y python3 python3-venv python3-pip openssh-server openssl

    id -u router >/dev/null 2>&1 || useradd -r -m -d /opt/llm-router -s /usr/sbin/nologin router
    mkdir -p /opt/llm-router
    chown router:router /opt/llm-router

    if [ ! -x /opt/llm-router/venv/bin/uvicorn ]; then
      sudo -u router bash -c '
        python3 -m venv /opt/llm-router/venv
        /opt/llm-router/venv/bin/pip install --upgrade pip
        /opt/llm-router/venv/bin/pip install \
            fastapi "uvicorn[standard]" httpx \
            slowapi prometheus-fastapi-instrumentator
      '
    fi

    # SSH hardening: disable password auth + root password login.
    # Operator must push their public key into /root/.ssh/authorized_keys before this lands.
    sed -i 's/^#*PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
    sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
    systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true
GUEST
}

phase_7_3_deploy_app() {
  step "7.3 — Deploy router app.py"
  pct push "$ROUTER_VMID" "$APP_SRC" /opt/llm-router/app.py --perms 0644
  pct exec "$ROUTER_VMID" -- chown router:router /opt/llm-router/app.py
}

phase_7_4_systemd() {
  step "7.4 — Install systemd unit (V620-only, EnvironmentFile loads API keys + admission)"
  pct exec "$ROUTER_VMID" -- env \
    "V620_URL=$V620_URL" \
    "EMBED_URL=$EMBED_URL" \
    "RERANK_URL=$RERANK_URL" \
    "KEEPALIVE_INTERVAL=$KEEPALIVE_INTERVAL" \
    "CHAT_CONCURRENCY=$CHAT_CONCURRENCY" \
    "EMBED_CONCURRENCY=$EMBED_CONCURRENCY" \
    "MAX_CHAT_INPUT_TOKENS=$MAX_CHAT_INPUT_TOKENS" \
    "MAX_EMBED_INPUT_TOKENS=$MAX_EMBED_INPUT_TOKENS" \
    "RATE_LIMIT_CHAT=$RATE_LIMIT_CHAT" \
    "RATE_LIMIT_EMBED=$RATE_LIMIT_EMBED" \
    "METRICS_ALLOWED_IPS=$METRICS_ALLOWED_IPS" \
    bash -se <<'GUEST'
    set -Eeuo pipefail

    # Persist admission/rate-limit/metrics config to /etc/router.env so EnvironmentFile picks them up.
    # API keys are already in /etc/router.env from phase 7.1.5.
    upsert_env() {
      local key="$1" val="$2"
      if grep -q "^${key}=" /etc/router.env 2>/dev/null; then
        sed -i "s|^${key}=.*|${key}=${val}|" /etc/router.env
      else
        echo "${key}=${val}" >> /etc/router.env
      fi
    }
    upsert_env V620_URL "$V620_URL"
    upsert_env EMBED_URL "$EMBED_URL"
    upsert_env RERANK_URL "$RERANK_URL"
    upsert_env KEEPALIVE_INTERVAL "$KEEPALIVE_INTERVAL"
    upsert_env CHAT_CONCURRENCY "$CHAT_CONCURRENCY"
    upsert_env EMBED_CONCURRENCY "$EMBED_CONCURRENCY"
    upsert_env MAX_CHAT_INPUT_TOKENS "$MAX_CHAT_INPUT_TOKENS"
    upsert_env MAX_EMBED_INPUT_TOKENS "$MAX_EMBED_INPUT_TOKENS"
    upsert_env RATE_LIMIT_CHAT "$RATE_LIMIT_CHAT"
    upsert_env RATE_LIMIT_EMBED "$RATE_LIMIT_EMBED"
    upsert_env METRICS_ALLOWED_IPS "$METRICS_ALLOWED_IPS"
    chmod 600 /etc/router.env

    cat > /etc/systemd/system/llm-router.service <<EOF
[Unit]
Description=LLM cluster router (V620-only — Bearer auth, admission control, Prometheus)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=router
WorkingDirectory=/opt/llm-router
EnvironmentFile=/etc/router.env
ExecStart=/opt/llm-router/venv/bin/uvicorn app:app \\
    --host 0.0.0.0 --port 8000 \\
    --timeout-keep-alive 300 \\
    --workers 1
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
    # Provision the access-log directory (writeable by the router user)
    mkdir -p /var/log/llm-router
    chown router:router /var/log/llm-router

    systemctl daemon-reload
    systemctl enable llm-router
    # restart so updated /etc/router.env values take effect on re-run
    systemctl restart llm-router
    systemctl status llm-router --no-pager || true
GUEST
}

phase_7_5_keepalive_timer() {
  step "7.5 — Install model-keepalive systemd timer (eliminates cold-start latency)"
  pct exec "$ROUTER_VMID" -- bash -se <<'GUEST'
    set -Eeuo pipefail
    # Tiny periodic ping to the chat model so its weights stay hot in VRAM. The
    # llamacpp-chat unit doesn't unload weights but the first request after a
    # long idle period eats a 2-5s warm-up. Hitting it every 5 minutes pre-warms
    # the cache and keeps p99 latency consistent.
    cat > /usr/local/bin/llm-router-keepalive.sh <<'SH'
#!/bin/bash
# Pings the chat model with a 1-token request. Fails silently if the router
# is unreachable (we don't want a paging dependency).
set -e
. /etc/router.env  # source ROUTER_API_KEY
curl -s -m 30 -o /dev/null \
    -H "Authorization: Bearer ${ROUTER_API_KEY}" \
    -H "Content-Type: application/json" \
    -d '{"model":"rag-qwen3.6","messages":[{"role":"user","content":"."}],"max_tokens":1}' \
    http://127.0.0.1:8000/v1/chat/completions || true
SH
    chmod +x /usr/local/bin/llm-router-keepalive.sh

    cat > /etc/systemd/system/llm-router-keepalive.service <<'EOF'
[Unit]
Description=Periodic warm-up ping to the LLM chat model
After=llm-router.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/llm-router-keepalive.sh
EOF

    cat > /etc/systemd/system/llm-router-keepalive.timer <<'EOF'
[Unit]
Description=Periodic warm-up ping every 5 minutes
After=llm-router.service

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
RandomizedDelaySec=20s

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now llm-router-keepalive.timer
    systemctl status llm-router-keepalive.timer --no-pager || true
GUEST
}

main() {
  phase_7_1_create
  phase_7_1_5_api_keys
  phase_7_2_python_env
  phase_7_3_deploy_app
  phase_7_4_systemd
  phase_7_5_keepalive_timer

  step "Phase 7 complete."
  local ip; ip="$(lxc_get_ip "$ROUTER_VMID" || true)"
  ok "Router ready at IP: ${ip:-unknown}"
  echo "  Smoke test:"
  echo "    curl -s http://${ip:-<router-ip>}:8000/healthz | jq"
  echo "    curl -s http://${ip:-<router-ip>}:8000/v1/models | jq"
}

main "$@"
