#!/usr/bin/env bash
# 54-lxc-anythingllm.sh — Phase 8 of setup-runbook.md.
#
# Provision LXC 154 (anythingllm):
#   - Unprivileged LXC with nesting=1,keyctl=1 for Docker
#   - Bind-mount /tank/anythingllm -> /opt/anythingllm-data
#   - Install Docker CE (modern DEB822 sources, docker.asc keyring)
#   - Deploy AnythingLLM via docker compose

set -Eeuo pipefail
LGC_DIR="${LGC_DIR:-$(cd "$(dirname "$0")" && pwd)}"
# shellcheck source=lib/common.sh
source "$LGC_DIR/lib/common.sh"

require_root
require_pve_host
load_config

ALLM_VMID="${ANYTHINGLLM_VMID:-154}"
ALLM_HOSTNAME="${ANYTHINGLLM_HOSTNAME:-anythingllm}"
ALLM_CORES="${ANYTHINGLLM_CORES:-4}"
# Bumped from 8 GB to 16 GB after 2026-05-18: with 700+ docs across multiple
# workspaces + heavy bulk ingest, AnythingLLM's Node V8 heap + lancedb index
# saturated 8 GB RAM and 512 MB swap (memory and swap both at 99%+ usage).
ALLM_MEMORY="${ANYTHINGLLM_MEMORY:-16384}"
ALLM_ROOTFS_SIZE="${ANYTHINGLLM_ROOTFS_SIZE:-32}"
LXC_STORAGE="${LXC_STORAGE:-local-lvm}"   # V620-only: ext4 + LVM-thin (was local-zfs)
BRIDGE="${BRIDGE:-vmbr0}"
LXC_TEMPLATE_NAME="${LXC_TEMPLATE_NAME:-ubuntu-24.04-standard_24.04-2_amd64.tar.zst}"
LXC_TEMPLATE_STORAGE="${LXC_TEMPLATE_STORAGE:-local}"
ALLM_STORAGE_MOUNT="${ALLM_STORAGE_MOUNT:-/tank/anythingllm}"

# ---------- AnythingLLM env-driven config ----------
# Points at the router. AnythingLLM hits /v1/chat/completions for the LLM and
# /v1/embeddings for the embedder; the router routes upstream by alias.
ROUTER_IP="${ROUTER_IP:-192.168.6.153}"
ALLM_LLM_BASE_URL="${ALLM_LLM_BASE_URL:-http://${ROUTER_IP}:8000/v1}"
ALLM_LLM_MODEL="${ALLM_LLM_MODEL:-rag-qwen3.6}"        # matches LLAMA_ALIAS in 51-lxc-amd.sh
# V620-only build: chat unit uses --ctx-size 131072 (128K). Higher values cause silent
# mid-conversation failure when AnythingLLM sends a request that exceeds llama.cpp's
# actual context. Pre-pivot configs used 262144 (256K) which was a bug.
ALLM_LLM_TOKEN_LIMIT="${ALLM_LLM_TOKEN_LIMIT:-131072}"
# AnythingLLM authenticates to the router using ROUTER_API_KEY (generated by 53-lxc-router.sh,
# stored in /etc/router.env on LXC 153). If empty here, the script will fetch it from LXC 153.
ALLM_LLM_API_KEY="${ALLM_LLM_API_KEY:-}"
ALLM_EMBED_BASE_URL="${ALLM_EMBED_BASE_URL:-http://${ROUTER_IP}:8000/v1}"
ALLM_EMBED_MODEL="${ALLM_EMBED_MODEL:-qwen3-embed}"
# Qwen3-Embedding-0.6B context = 8K (--ctx-size 8192 in llamacpp-embed.service).
ALLM_EMBED_MAX_CHUNK="${ALLM_EMBED_MAX_CHUNK:-16384}"  # must match LXC 153 MAX_EMBED_INPUT_TOKENS and LXC 151 per-slot embed ctx
ALLM_EMBED_API_KEY="${ALLM_EMBED_API_KEY:-}"           # same ROUTER_API_KEY as LLM
ALLM_EMBED_CONCURRENT="${ALLM_EMBED_CONCURRENT:-8}"

# Fetch ROUTER_API_KEY from LXC 153 if not provided explicitly
if [[ -z "$ALLM_LLM_API_KEY" ]]; then
  ALLM_LLM_API_KEY="$(pct exec ${ROUTER_VMID:-153} -- awk -F= '/^ROUTER_API_KEY=/{print $2}' /etc/router.env 2>/dev/null || true)"
  [[ -n "$ALLM_LLM_API_KEY" ]] || warn "ROUTER_API_KEY not found on LXC 153. Run 53-lxc-router.sh first, then re-run this script."
fi
ALLM_EMBED_API_KEY="${ALLM_EMBED_API_KEY:-$ALLM_LLM_API_KEY}"

# 32+ char secrets required for production. Generated on first run if blank.
ALLM_JWT_SECRET="${ALLM_JWT_SECRET:-}"
ALLM_SIG_KEY="${ALLM_SIG_KEY:-}"
ALLM_SIG_SALT="${ALLM_SIG_SALT:-}"

phase_8_1_create() {
  step "8.1 — Create LXC $ALLM_VMID ($ALLM_HOSTNAME)"
  if lxc_exists "$ALLM_VMID"; then
    skip "LXC $ALLM_VMID already exists."
    return 0
  fi
  pct create "$ALLM_VMID" "$LXC_TEMPLATE_STORAGE:vztmpl/$LXC_TEMPLATE_NAME" \
    --hostname "$ALLM_HOSTNAME" \
    --cores "$ALLM_CORES" \
    --memory "$ALLM_MEMORY" \
    --swap 2048 \
    --rootfs "${LXC_STORAGE}:${ALLM_ROOTFS_SIZE}" \
    --net0 "name=eth0,bridge=${BRIDGE},firewall=0,ip=dhcp,type=veth" \
    --features "nesting=1,keyctl=1" \
    --unprivileged 1 \
    --ostype ubuntu \
    --onboot 1 \
    --startup order=3,up=5 \
    --start 0
}

phase_8_2_bind_mount() {
  step "8.2 — Bind-mount $ALLM_STORAGE_MOUNT into LXC"
  mkdir -p "$ALLM_STORAGE_MOUNT"
  # Unprivileged LXC: container-root (UID 0) maps to host UID 100000. Without this chown,
  # mkdir inside the LXC under /opt/anythingllm-data/ fails with EACCES. Idempotent.
  if [[ "$(stat -c '%u:%g' "$ALLM_STORAGE_MOUNT")" != "100000:100000" ]]; then
    chown -R 100000:100000 "$ALLM_STORAGE_MOUNT"
  fi
  pct_set_if_changed "$ALLM_VMID" mp0 "$ALLM_STORAGE_MOUNT,mp=/opt/anythingllm-data"
  ensure_lxc_started "$ALLM_VMID"
}

phase_8_3_docker() {
  step "8.3 — Install Docker CE"
  if pct exec "$ALLM_VMID" -- bash -c 'command -v docker >/dev/null 2>&1'; then
    skip "Docker already installed."
    return 0
  fi

  pct exec "$ALLM_VMID" -- bash -se <<'GUEST'
    set -Eeuo pipefail
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt install -y ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Modern DEB822 sources format (replaces sources.list)
    cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

    apt update
    apt install -y docker-ce docker-ce-cli containerd.io \
                   docker-buildx-plugin docker-compose-plugin

    systemctl enable --now docker
    docker run --rm hello-world
GUEST
}

phase_8_4_compose() {
  step "8.4 — Deploy AnythingLLM docker compose stack (env-driven)"

  # Generate secrets on the host if blank, so we keep them stable across re-runs.
  if [[ -z "$ALLM_JWT_SECRET" || -z "$ALLM_SIG_KEY" || -z "$ALLM_SIG_SALT" ]]; then
    local secrets_file="/var/lib/anythingllm-secrets.env"
    if [[ -f "$secrets_file" ]]; then
      # shellcheck disable=SC1090
      source "$secrets_file"
    else
      log "Generating AnythingLLM secrets (saved to $secrets_file)"
      ALLM_JWT_SECRET="$(openssl rand -hex 24)"
      ALLM_SIG_KEY="$(openssl rand -hex 32)"
      ALLM_SIG_SALT="$(openssl rand -hex 32)"
      umask 077
      cat > "$secrets_file" <<EOF
ALLM_JWT_SECRET=$ALLM_JWT_SECRET
ALLM_SIG_KEY=$ALLM_SIG_KEY
ALLM_SIG_SALT=$ALLM_SIG_SALT
EOF
    fi
  fi

  pct exec "$ALLM_VMID" -- env \
    "ALLM_LLM_BASE_URL=$ALLM_LLM_BASE_URL" \
    "ALLM_LLM_MODEL=$ALLM_LLM_MODEL" \
    "ALLM_LLM_TOKEN_LIMIT=$ALLM_LLM_TOKEN_LIMIT" \
    "ALLM_LLM_API_KEY=$ALLM_LLM_API_KEY" \
    "ALLM_EMBED_BASE_URL=$ALLM_EMBED_BASE_URL" \
    "ALLM_EMBED_MODEL=$ALLM_EMBED_MODEL" \
    "ALLM_EMBED_MAX_CHUNK=$ALLM_EMBED_MAX_CHUNK" \
    "ALLM_EMBED_API_KEY=$ALLM_EMBED_API_KEY" \
    "ALLM_EMBED_CONCURRENT=$ALLM_EMBED_CONCURRENT" \
    "ALLM_JWT_SECRET=$ALLM_JWT_SECRET" \
    "ALLM_SIG_KEY=$ALLM_SIG_KEY" \
    "ALLM_SIG_SALT=$ALLM_SIG_SALT" \
    bash -se <<'GUEST'
    set -Eeuo pipefail
    mkdir -p /opt/anythingllm /opt/anythingllm-data/storage
    # AnythingLLM image runs as UID 1000 (anythingllm user). Without this chown,
    # the container crash-loops on Prisma "unable to open database file" because
    # the storage dir is owned by container-root. Per Mintplex Docker docs.
    chown -R 1000:1000 /opt/anythingllm-data

    # Pinning to :latest is OK for a personal lab; pin to a digest if you need
    # reproducible builds. The image takes ~5 min to pull on first run.
    cat > /opt/anythingllm/docker-compose.yml <<'EOF'
services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "3001:3001"
    env_file: /opt/anythingllm/.env
    volumes:
      - /opt/anythingllm-data/storage:/app/server/storage
EOF

    # Pre-populate .env so AnythingLLM boots with the cluster wired in.
    # Documented vars from Mintplex-Labs/anything-llm docker/.env.example.
    cat > /opt/anythingllm/.env <<EOF
SERVER_PORT=3001
STORAGE_DIR=/app/server/storage
JWT_SECRET=${ALLM_JWT_SECRET}
SIG_KEY=${ALLM_SIG_KEY}
SIG_SALT=${ALLM_SIG_SALT}

# LLM provider (router -> V620 by default; clients can pick fast-chat by name)
LLM_PROVIDER=generic-openai
GENERIC_OPEN_AI_BASE_PATH=${ALLM_LLM_BASE_URL}
GENERIC_OPEN_AI_MODEL_PREF=${ALLM_LLM_MODEL}
GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT=${ALLM_LLM_TOKEN_LIMIT}
GENERIC_OPEN_AI_API_KEY=${ALLM_LLM_API_KEY}

# Embedder (router -> V620 Qwen3-Embedding-0.6B, 1024-dim, --pooling last)
EMBEDDING_ENGINE=generic-openai
EMBEDDING_BASE_PATH=${ALLM_EMBED_BASE_URL}
EMBEDDING_MODEL_PREF=${ALLM_EMBED_MODEL}
EMBEDDING_MODEL_MAX_CHUNK_LENGTH=${ALLM_EMBED_MAX_CHUNK}
GENERIC_OPEN_AI_EMBEDDING_API_KEY=${ALLM_EMBED_API_KEY}
GENERIC_OPEN_AI_EMBEDDING_MAX_CONCURRENT_CHUNKS=${ALLM_EMBED_CONCURRENT}

# Vector store
VECTOR_DB=lancedb

# Disable telemetry (lab cluster)
DISABLE_TELEMETRY=true
EOF
    chmod 600 /opt/anythingllm/.env

    cd /opt/anythingllm
    docker compose pull
    docker compose up -d
GUEST
}

main() {
  phase_8_1_create
  phase_8_2_bind_mount
  phase_8_3_docker
  phase_8_4_compose

  step "Phase 8 complete."
  local ip; ip="$(lxc_get_ip "$ALLM_VMID" || true)"
  ok "AnythingLLM ready at: http://${ip:-<allm-ip>}:3001"
  echo "  Configure via UI:"
  echo "    Settings -> AI Providers -> LLM: Generic OpenAI"
  echo "      Base URL: http://${ROUTER_IP:-<router-ip>}:8000/v1"
  echo "    Settings -> AI Providers -> Embedder: Generic OpenAI"
  echo "      Base URL: http://${ROUTER_IP:-<router-ip>}:8000/v1   (dim 1024)"
  echo "    Settings -> Text Splitter -> chunk=2500, overlap=500"
}

main "$@"
