#!/usr/bin/env bash
# 58-rag-refresh-timer.sh — Phase 3 of the RAG roadmap (scripts/rag/README.md).
#
# Schedules scripts/rag/refresh.py to run automatically on the PVE host so
# corpora stay current without manual intervention. Also emits a Prometheus
# textfile-format metrics file after each run for monitoring.
#
# Components installed:
#   /usr/local/bin/rag-refresh-wrapper.sh  — invokes refresh.py via the
#                                            scraper venv, captures metrics
#   /etc/systemd/system/rag-refresh.service — oneshot, runs the wrapper
#   /etc/systemd/system/rag-refresh.timer   — daily schedule
#   /var/lib/rag-refresh/metrics.prom       — last-run metrics (textfile format)
#   /var/lib/rag-refresh/last-run.log       — last-run console log (overwrites)
#
# Why on the PVE host (not in an LXC): refresh.py needs read access to
# /tank/rag-state, write access to /tank/rag-state, the existing
# /opt/vcf-scraper-venv (trafilatura + requests + pyyaml), and outbound HTTP
# to AnythingLLM at 192.168.6.154:3001. The host has all of those; the
# router LXC doesn't have the venv and the AnythingLLM LXC doesn't have
# direct /tank access.
#
# Schedule rationale: daily at 03:15 UTC (after off-hours, ZFS snapshots
# typically run around 02:00). Per-source refresh_interval still gates
# whether each source actually executes — the timer just gives them a
# regular opportunity. Override via REFRESH_TIMER_SCHEDULE env var.
#
# Idempotent — re-running rewrites the unit files and re-enables the timer.

set -Eeuo pipefail
LGC_DIR="${LGC_DIR:-$(cd "$(dirname "$0")" && pwd)}"
# shellcheck source=lib/common.sh
source "$LGC_DIR/lib/common.sh"

require_root
require_pve_host
load_config

REFRESH_SCRIPT="${REFRESH_SCRIPT:-${LGC_DIR}/rag/refresh.py}"
SCRAPER_VENV="${SCRAPER_VENV:-/opt/vcf-scraper-venv}"
REFRESH_TIMER_SCHEDULE="${REFRESH_TIMER_SCHEDULE:-*-*-* 03:15:00}"
REFRESH_STATE_DIR="${REFRESH_STATE_DIR:-/var/lib/rag-refresh}"
RAG_STATE_DIR="${RAG_STATE_DIR:-/tank/rag-state}"

[[ -f "$REFRESH_SCRIPT" ]] || die "refresh.py not found at $REFRESH_SCRIPT (LGC_DIR=$LGC_DIR)"

step "58.1 — Ensure scraper venv exists with required deps"
if [[ ! -x "$SCRAPER_VENV/bin/python" ]]; then
  log "creating $SCRAPER_VENV (PyYAML + requests + trafilatura)"
  python3 -m venv "$SCRAPER_VENV"
  "$SCRAPER_VENV/bin/pip" install -q --upgrade pip
  "$SCRAPER_VENV/bin/pip" install -q -r "${LGC_DIR}/rag/requirements.txt"
else
  skip "scraper venv already exists at $SCRAPER_VENV"
fi

step "58.2 — Ensure metrics + log directory exists"
mkdir -p "$REFRESH_STATE_DIR"
chmod 0755 "$REFRESH_STATE_DIR"

step "58.3 — Install /usr/local/bin/rag-refresh-wrapper.sh"
cat > /usr/local/bin/rag-refresh-wrapper.sh <<EOF
#!/bin/bash
# Auto-generated by 58-rag-refresh-timer.sh. Don't hand-edit — re-run the
# phase script to regenerate.
#
# Wraps refresh.py with timing + Prometheus textfile metrics emission.
# Exit code propagates from refresh.py (1 if any source errored / halted).
set -u
SCRAPER_VENV="$SCRAPER_VENV"
REFRESH_SCRIPT="$REFRESH_SCRIPT"
METRICS_FILE="$REFRESH_STATE_DIR/metrics.prom"
LAST_LOG="$REFRESH_STATE_DIR/last-run.log"

export RAG_METRICS_FILE="\$METRICS_FILE"

# Run refresh, tee output to log AND journal. We use \`script -q -c\` to keep
# refresh.py's progress-bar / heartbeat printing visible in real time in the
# journal (otherwise stdio buffering collects it into one big chunk at end).
rc=0
"\$SCRAPER_VENV/bin/python" "\$REFRESH_SCRIPT" 2>&1 | tee "\$LAST_LOG" || rc=\$?

# Even if refresh exited non-zero, leave the metrics file in place for the
# scrape — it'll have rag_refresh_errors_total > 0 which is the alert signal.
exit \$rc
EOF
chmod 0755 /usr/local/bin/rag-refresh-wrapper.sh
chown root:root /usr/local/bin/rag-refresh-wrapper.sh

step "58.4 — Install rag-refresh.service + .timer"
cat > /etc/systemd/system/rag-refresh.service <<EOF
[Unit]
Description=RAG corpus refresh (scripts/rag/refresh.py via $SCRAPER_VENV)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
TimeoutStartSec=4h
ExecStart=/usr/local/bin/rag-refresh-wrapper.sh
StandardOutput=journal
StandardError=journal
EOF

cat > /etc/systemd/system/rag-refresh.timer <<EOF
[Unit]
Description=Daily RAG corpus refresh
After=network-online.target

[Timer]
OnCalendar=$REFRESH_TIMER_SCHEDULE
RandomizedDelaySec=10min
Persistent=true
Unit=rag-refresh.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now rag-refresh.timer

step "58.5 — Smoke-check timer state"
systemctl list-timers rag-refresh.timer --no-pager || true

ok "Phase 58 complete."
echo
echo "Timer schedule:        $REFRESH_TIMER_SCHEDULE (with up to 10min randomized delay)"
echo "Per-source gating:     refresh_interval in sources.yaml (timer doesn't bypass it)"
echo "Manual run:            systemctl start rag-refresh.service"
echo "Tail the run:          journalctl -u rag-refresh.service -f"
echo "Last-run log:          $REFRESH_STATE_DIR/last-run.log"
echo "Prometheus metrics:    $REFRESH_STATE_DIR/metrics.prom"
echo "Next scheduled run:    $(systemctl list-timers rag-refresh.timer --no-pager 2>/dev/null | awk 'NR==2 {print $1, $2}')"
